### PR TITLE
Add Exception handling.

### PR DESCRIPTION
**Pull request by smeinecke**
Add Exception handling for failed requests in phantomjs.

### CODE REVIEW

**Comment by fzaninotto** [comment]
Thanks!

**Comment by Metaboll** [comment]
Hi,

I Start to work with your Codeflower and Event-drops. My oppinion about this two codes are incredible.

I'm a civil engeneering, and I have a programing hobby. I start to play with codeflower for construction butget visualizations and eventdrops for technical planification use.

In the case of event-drops I want to put one more child property data ----> duration task. I change the circle shape to rectangular shape but it was imposible for me to get the data duration information and in this case put the width property scalable to duration task property.

My problem is with /sc/evenDrop.js code file.

var o=function(e){
                                    e.each(function(){
                                        d3.select(this).selectAll.....................................
var e=d3.select(this).selectAll("rect")
                                    .data(function(e){return r(e.dates,t.xScale)});

```
                            e.enter()
                                //.append("circle")
                                .append("rect")
                                //.attr("cx",function(e){return t.xScale(e)})
                                .attr("x",function(e){return t.xScale(e)})
                                .attr("y",-5)
                                //.attr("cy",-5)
                                //.attr("r",10);
                                .attr("height",10)//
                                .attr("width",function(e){return e.duration})
                                //console.log(e.duration);
```

I am not capable to put e.duration information from json data inside the attr properties. Could you help me? Thanks, Fernando.

It is amazing to see economics construction site butgets in your graphics......

**Comment by jayvi** [comment]
Hi,

I am working on a project where its need to have a url to screenshot feature and test your screenshot-as-a-service but my problem is the flash websites. My question is do you know how to fix it or is that functionality will be included soon? 

Cheers

**Comment by fzaninotto** [comment]
@Metaboll @jayvi I don't see the relation with this issue. Please open a new issue on the right repository.

**Pull request merged**
